config/routes.rb
Rails.application.routes.draw do
  get     'sessions/new'
  root    'static_pages#home'
  get     '/about',   to: 'static_pages#about'

  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  delete  '/logout',   to: 'sessions#destroy'

  resources :users, except: :new
  resources :sessions, only: :create
  resources :microposts, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user #this associate already includes validation for user_id
  mount_uploader :picture, PictureUploader
  validates :content, presence: true, length: { maximum: 250 }
  validate :picture_size

  private
    def picture_size
      errors.add(:picture, "should be less than 5mb") if picture.size > 5.megabytes
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts

  # Filter method to transform email to small cases before saving to db
  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }

  # REGEX = Regular expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    @micropost = current_user.microposts.build(micropost_params)

    if @micropost.save
      redirect_to root_url
    else
      # home_feed view needs this variable, to display microposts
      @microposts = current_user.microposts.paginate(page: params[:page])
      render 'users/home_feed'
    end
  end

  def destroy
    micropost = Micropost.find(params[:id])
    micropost.destroy

    redirect_to root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)  
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:info] = "Successfully logged in."
      redirect_to root_url
    else
      flash[:danger] = "Invalid credentials."
      redirect_to login_url
    end
  end

  def destroy
    log_out
    flash[:info] = "Successfully logged out"

    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # Different home view if there is a logged user
    if logged_in?
      @micropost = Micropost.new

      # To be updated after follow function
      @microposts = current_user.microposts.order(created_at: :desc).paginate(page: params[:page], per_page: 10)

      render 'users/home_feed'
    end
  end

  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :require_admin, only: :destroy
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to edit_user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    flash[:info] = "Deleted user: #{user.email}"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def require_login
      unless logged_in?
        flash[:info] = "Please log in."
        redirect_to login_url
      end
    end

    def require_admin
      redirect_to(root_path) unless current_user.admin?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    current_user == user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    # Generates hex token
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    image_size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{image_size}"

    # Creates img element
    image_tag(gravatar_url, alt: user.name)
  end
end

app/views/layouts/_footer.html.erb
<footer class="border-top p-3">
    <div class="container">
        <small class="float-left">Awesomeblog application &copy; Framgia PH </small>

        <ul class="float-right">
            <li class="d-inline-block">
                <small><%= link_to "Home", root_path, class: "text-muted" %></small>
            </li>
            <li class="d-inline-block">
                <small><%= link_to "About", about_path, class: "text-muted" %></small>
            </li>
        </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <strong><%= link_to "awesomeblog", root_path, class: "navbar-brand" %></strong>

        <!-- A toggle button for mobile view -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>

                <% if logged_in? %>
                    <li class="nav-item">
                        <%= link_to "Users", users_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"><%= current_user.name %></a>

                        <div class="dropdown-menu">
                            <%= link_to "Profile", current_user, class: "dropdown-item" %>
                            <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
                            <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign up", signup_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log in", login_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>FphRailsAwesomeblog</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'layouts/header' %>

        <div class="container p-3">
            <% if flash.any? %>
                <% flash.each do |type, msg| %>
                    <div class="alert alert-<%= type %>">
                        <div><%= msg %></div>
                    </div>
                <% end %>
            <% end %>

            <%= yield %>

            <!-- To display the current logged in user -->
            <%#= debug session[:user_id] if Rails.env == 'development' %>
        </div>

        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/microposts/_micropost.html.erb
<li class="media py-3 px-2 border-top">
    <!-- belongs_to :user -->
    <div class="mr-2">
        <%= link_to gravatar_for(micropost.user, size: 60), micropost.user %>
    </div>

    <div class="media-body">
        <h5><%= link_to micropost.user.name, micropost.user %></h5>
        <div><%= micropost.content %></div>
        
        <% if micropost.picture? %>
            <div>
                <%= image_tag micropost.picture.url, class: "mw-100" %>
            </div>
        <% end %>

        <small class="text-muted">Posted <%= time_ago_in_words(micropost.created_at) %> ago</small>
    </div>

    <%= link_to micropost, method: :delete,
                data: { confirm: "Are you sure?" },
                class: "float-right" do %>
        <i class="fa fa-times text-muted"></i>
    <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>

    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <hr>
<% end %>

app/views/static_pages/about.html.erb
<div class="jumbotron">
    <h1>About</h1>
    <p>This is a Ruby on Rails application. A project by <em>Kredo PH</em> and <em>Framgia PH</em>.</p>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
    <h1><strong>Awesomeblog app</strong></h1>
    <p>Welcome to awesomeblog!</p>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit btn_msg, class: 'btn btn-primary btn-block' %>
<% end %>

app/views/users/edit.html.erb
<div class="col-sm-6 mx-auto">
    <h1 class="text-center border-bottom p-4 mb-3">Settings</h1>

    <%= render 'form', btn_msg: "Edit account" %>
</div>

app/views/users/home_feed.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="card mb-3">
            <div class="card-body text-center">
                <%= gravatar_for current_user %>

                <h1><%= current_user.name %></h1>
                <%= current_user.email %>

                <hr>

                <div class="row">
                    <div class="col">
                        <h4 class="font-weight-bold text-muted m-0">
                            <%= link_to current_user.microposts.count, current_user %>
                        </h4>
                        <small><%= "micropost".pluralize(current_user.microposts.count) %></small>
                    </div>
                    <div class="col">
                        <h4 class="font-weight-bold text-muted m-0">40</h4>
                        <small>followers</small>
                    </div>
                    <div class="col">
                        <h4 class="font-weight-bold text-muted m-0">40</h4>
                        <small>following</small>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <%= form_for(@micropost) do |f| %>
                    <%= render 'shared/error_messages', object: f.object %>

                    <div class="form-group">
                        <%= f.text_area :content, class: "form-control", placeholder: "Share your thoughts...", rows: 5 %>
                    </div>

                    <div class="form-group">
                        <%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png", class: "mt-2" %>
                    </div>

                    <%= f.submit "Post", class: "btn btn-primary btn-block"%>
                <% end %>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h4>Feed</h3>

                <% if @microposts.any? %>
                    <!-- rendering a collection: micropost/_micropost.html.erb -->
                    <ul class="list-unstyled">
                        <%= render @microposts %>
                    </ul>
                <% else %>
                    <div class="text-muted">Nothing to show</div>
                <% end %>
            </div>

            <div class="card-footer paginate text-center">
                <!-- Pass the collection to this method, because the controller name for this is not microposts, but static_pages -->
                <%= will_paginate @microposts if @microposts.any? %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center border-bottom p-4 mb-3">Users</h1>

<div class="paginate text-right">
    <%= will_paginate %>
</div>

<div class="row">
    <% @users.each do |user| %>
        <div class="col-sm-6">
            <div class="media mb-3">    
                <div class="align-self-center mr-3 border">
                    <%= link_to gravatar_for(user), user %>
                </div>

                <div class="media-body">
                    <h4><%= link_to user.name, user %></h4>
                </div>

                <% if current_user.admin? && !current_user?(user) %>
                    <%= link_to "Delete",   user, method: :delete,
                                            class: "btn btn-outline-danger btn-sm float-right",
                                            data: { confirm: "Are you sure?" } %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div class="paginate text-center border-top pt-3">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="col-sm-6 mx-auto">
    <h1 class="text-center border-bottom p-4 mb-3">Sign up</h1>

    <%= render 'form', btn_msg: "Create a new account" %>
</div>

app/views/users/show.html.erb
<div class="jumbotron p-3 px-5">
    <div class="row">
        <div class="col-md-10">  
            <div class="media">
                <div class="mr-3 align-self-center">
                    <%= gravatar_for @user, size: 120 %>
                </div>

                <div class="media-body my-auto">
                    <h1><%= @user.name %></h1>
                </div>
            </div>
        </div>
        <div class="col-md-2 text-center">
            <strong style="font-size: 3rem;"><%= @microposts.count %></strong><br>
            <span class="text-muted"><%= "microposts".pluralize(@microposts.count) %></span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8 mx-auto">
        <% if @microposts.any? %>
            <ul class="list-unstyled">
                <%= render @microposts %>
            </ul>

            <div class="paginate text-center">
                <%= will_paginate @microposts %>
            </div>
        <% end %>
    </div>
</div>